environment:
    matrix:
      # node.js
      - nodejs_version: "6"
      - nodejs_version: "7"
      - nodejs_version: "8"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run bootstrap

test_script:
  - node --version
  - npm --version
  - npm test

# Don't actually build.
build: off
